Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ges_commande.Models.entity;
using GesCommande.core;

namespace ges_commande.Controllers
{
    public class ClientController : Controller
    {
        private readonly Context _context;

        public ClientController(Context context)
        {
            _context = context;
        }

        // GET: Client
        public async Task<IActionResult> Index()
        {
            var context = _context.Clients.Include(c => c.User);
            return View(await context.ToListAsync());
        }

        // GET: Client/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Client/Create
        public IActionResult Create()
        {
            ViewData["usersId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Client/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Solde,Adresse,usersId,Nom,Prenom,Telephone,CreateAt,UpdateAt")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["usersId"] = new SelectList(_context.Users, "Id", "Id", client.UserId);
            return View(client);
        }

        // GET: Client/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            ViewData["usersId"] = new SelectList(_context.Users, "Id", "Id", client.UserId);
            return View(client);
        }

        // POST: Client/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Solde,Adresse,usersId,Nom,Prenom,Telephone,CreateAt,UpdateAt")] Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["usersId"] = new SelectList(_context.Users, "Id", "Id", client.UserId);
            return View(client);
        }

        // GET: Client/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .Include(c => c.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Client/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Clients.FindAsync(id);
            if (client != null)
            {
                _context.Clients.Remove(client);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
            return _context.Clients.Any(e => e.Id == id);
        }

//       public async Task<IActionResult> Clientviews(int? id)
// {
//     if (id == null)
//     {
//         return NotFound();
//     }

//     // Charger les produits (par exemple, tous les produits ou filtrés par un critère)
//     var produits = await _context.Produits.ToListAsync();

//     if (produits == null || !produits.Any())
//     {
//         return NotFound();
//     }

//     // Passer les produits à la vue
//     return View(produits);
// }

    }
}

Controllers/ProduitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ges_commande.Models.entity;
using GesCommande.core;

namespace ges_commande.Controllers
{
    public class ProduitController : Controller
    {
        private readonly Context _context;
        private readonly string _baseImageUrl = "http://localhost:5204/images";

        public ProduitController(Context context)
        {
            _context = context;
        }

        [Route("Produit/MesProduit")]
        public async Task<IActionResult> MesProduit(string disponibilite = "")
        {
            var query = _context.Produits.AsQueryable();

            if (disponibilite == "true")
            {
                query = query.Where(p => p.Quantite > 0);
            }
            else if (disponibilite == "false")
            {
                query = query.Where(p => p.Quantite <= 0);
            }

            ViewBag.Disponibilite = disponibilite;
            return View(await query.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produits.FirstOrDefaultAsync(m => m.Id == id);
            if (produit == null)
            {
                return NotFound();
            }

            return View(produit);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Libelle,Prix,Quantite,Id,CreateAt,UpdateAt")] Produit produit, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null && image.Length > 0)
                {
                    var imageFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images");
                    if (!Directory.Exists(imageFolder))
                    {
                        Directory.CreateDirectory(imageFolder);
                    }

                    var fileName = Guid.NewGuid() + Path.GetExtension(image.FileName);
                    var filePath = Path.Combine(imageFolder, fileName);

                    try
                    {
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await image.CopyToAsync(stream);
                        }

                        produit.image = $"{_baseImageUrl}/{fileName}";
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", "Erreur lors de l'upload de l'image : " + ex.Message);
                        return View(produit);
                    }
                }

                try
                {
                    _context.Add(produit);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(MesProduit));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Erreur lors de l'enregistrement du produit : " + ex.Message);
                }
            }

            return View(produit);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produits.FindAsync(id);
            if (produit == null)
            {
                return NotFound();
            }

            return View(produit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Libelle,Prix,Quantite,Id,CreateAt,UpdateAt")] Produit produit)
        {
            if (id != produit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProduitExists(produit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(MesProduit));
            }

            return View(produit);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produits.FirstOrDefaultAsync(m => m.Id == id);
            if (produit == null)
            {
                return NotFound();
            }

            return View(produit);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produit = await _context.Produits.FindAsync(id);
            if (produit != null)
            {
                _context.Produits.Remove(produit);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(MesProduit));
        }

        private bool ProduitExists(int id)
        {
            return _context.Produits.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Clientviews()
        {
            var produits = await _context.Produits.ToListAsync();

            if (produits == null || !produits.Any())
            {
                return NotFound();
            }

            return View(produits);
        }

        public async Task<IActionResult> Panier()
        {
            var produits = await _context.Produits.ToListAsync();
            return View(produits);
        }

        public async Task<IActionResult> Supprimer(int id)
        {
            var produit = await _context.Produits.FindAsync(id);
            if (produit != null)
            {
                _context.Produits.Remove(produit);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Panier");
        }

        public IActionResult Commander()
        {
            return RedirectToAction("Panier");
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ges_commande.Models.entity;
using GesCommande.core;

namespace ges_commande.Controllers
{
    public class UserController : Controller
    {
        private readonly Context _context;

        public UserController(Context context)
        {
            _context = context;
        }

        // GET: User
        public async Task<IActionResult> MesUser()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: User/Details/5  
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: User/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("login,password,role,Id,Nom,Prenom,Telephone,CreateAt,UpdateAt")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: User/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: User/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("login,password,role,Id,Nom,Prenom,Telephone,CreateAt,UpdateAt")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: User/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

Views/Shared/MenuClient.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | GesCommande</title>
    
    <!-- Stylesheets -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/output.css" asp-append-version="true" /> <!-- Tailwind CSS output -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GesDetteWeb.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css" rel="stylesheet" />
</head>
<body class="bg-gray-100 dark:bg-gray-900">
    <header>
        <!-- Navbar -->
        <nav class="border-gray-200 bg-gray-800 dark:bg-gray-800 dark:border-gray-700">
            <div class="max-w-screen-xl flex items-center justify-between mx-auto p-4">
                <a href="/Produit/Clientviews" class="flex items-center space-x-3 rtl:space-x-reverse">
                    <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
                    <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">GesDetteWeb</span>
                </a>

                <!-- Navbar links -->
                <div class="flex space-x-4">
                    <a href="@Url.Action("CommandeClient", "Commande")" class="text-white hover:bg-gray-700 rounded px-3 py-2">Mes Commande</a>
                    <!-- Panier Link -->
                    <a href="@Url.Action("Panier", "Produit")" class="text-white hover:bg-gray-700 rounded px-3 py-2">Panier</a>
                    <!-- Mes Commandes Link -->
                    <a href="@Url.Action("Logout", "securite")" class="text-white hover:bg-gray-700 rounded px-3 py-2">Deconnexion</a>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container mx-auto">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <footer class="border-t footer text-muted">
        <div class="container py-3">
            &copy; 2024 - GesCommande - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script> <!-- jQuery -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script> <!-- Flowbite -->
    <script src="~/js/site.js" asp-append-version="true"></script> <!-- Votre JS personnalisé -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | GesCommande</title>
    
    <!-- Stylesheets -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/output.css" asp-append-version="true" /> <!-- Tailwind CSS output -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GesDetteWeb.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css" rel="stylesheet" />
</head>
<body class="bg-gray-100 dark:bg-gray-900">
    <header>
        <!-- Navbar -->
        <nav class="border-gray-200 bg-gray-800 dark:bg-gray-800 dark:border-gray-700">
            <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
                <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
                    <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
                    <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">GesDetteWeb</span>
                </a>
                <button data-collapse-toggle="navbar-hamburger" type="button" class="inline-flex items-center justify-center p-2 w-10 h-10 text-sm text-gray-500 rounded-lg hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-hamburger" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>
                    <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
                    </svg>
                </button>
                <div class="hidden w-full" id="navbar-hamburger">
                    <ul class="flex flex-col font-medium mt-4 rounded-lg bg-gray-800 dark:bg-gray-800 dark:border-gray-700 text-sm text-gray-500">
                        <!-- Client Link -->
                        <li>
                            <a href="@Url.Action("Index", "Client")" class="block py-2 px-3 text-white rounded hover:text-white hover:bg-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">Clients</a>
                        </li>
                        <!-- Articles Link -->
                        <li>
                            <a href="@Url.Action("MesProduit", "Produit")" class="block py-2 px-3 text-white rounded hover:text-white hover:bg-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">Produit</a>
                        </li>
                        <!-- User Link -->
                        <li>
                            <a href="@Url.Action("MesUser", "User")" class="block py-2 px-3 text-white rounded hover:text-white hover:bg-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">Users</a>
                        </li>
                        <!-- Dettes Link -->
                        <li>
                            <a href="@Url.Action("CommandeRS", "Commande")" class="block py-2 px-3 text-white rounded hover:text-white hover:bg-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">Commande</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container mx-auto">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <footer class="border-t footer text-muted">
        <div class="container py-3">
            &copy; 2024 - GesCommande - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Scripts -->
 <script src="~/lib/jquery/dist/jquery.min.js"></script> <!-- jQuery -->
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> <!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script> <!-- Flowbite -->
<script src="~/js/site.js" asp-append-version="true"></script> <!-- Votre JS personnalisé -->
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>