Models/entity/Commande.cs
using ges_commande.Models.Enum;

namespace ges_commande.Models.entity
{
   public class Commande: AbstractEntity
    {
        public int Id { get; set; }
        public DateTime dateTime{ get; set; }

        public double montant { get; set; }

        public Client Client{ get; set; }
        public int ClientId{ get; set; }
        public Livreur Livreur{ get; set; }
        public int? livreurID{ get; set; }

        public List<DetailCommande> detailCommandes{ get; set; }

        public Paiement? Paiement{ get; set; }   
        public int PaiementId{ get; set; }
        public Etat Etat { get; set; }= Etat.Encours;

       
    }
}

Controllers/CommandeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ges_commande.Models.entity;
using GesCommande.core;
using ges_commande.Models.Enum;

namespace ges_commande.Controllers
{
    public class CommandeController : Controller
    {
        private readonly Context _context;

        public CommandeController(Context context)
        {
            _context = context;
        }

public IActionResult CommandeClient(string etat)
{
    // Vérifier si l'utilisateur est authentifié
    if (!User.Identity.IsAuthenticated)
    {
        return RedirectToAction("Login", "Securite"); // Rediriger vers la page de connexion si l'utilisateur n'est pas authentifié
    }

    var userName = User.Identity.Name;

    var utilisateur = _context.Users
                          .FirstOrDefault(u => u.login == userName); // Assurez-vous que "Nom" est le champ que vous utilisez pour stocker le nom d'utilisateur

    if (utilisateur == null)
    {
        return RedirectToAction("Login", "Securite"); // Si l'utilisateur n'est pas trouvé, rediriger vers la page de connexion
    }

    var clientId = utilisateur.Id;

    // Filtrer les commandes associées à cet utilisateur (client)
    var commandes = _context.Commandes
                             .Where(c => c.ClientId == clientId) // Assurez-vous que clientID fait référence à l'ID du client
                             .ToList();

     if (!string.IsNullOrEmpty(etat))
    {
commandes = commandes.Where(c => c.Etat == EtatHelper.GetValue(etat)).ToList();
    }

    // Passer la liste des commandes à la vue
    return View(commandes);
}

        // GET: Commande
        public async Task<IActionResult> MesCommande()
        {
            var context = _context.Commandes.Include(c => c.Client).Include(c => c.Livreur);
            return View(await context.ToListAsync());
        }

        // GET: Commande/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commande = await _context.Commandes
                .Include(c => c.Client)
                .Include(c => c.Livreur)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (commande == null)
            {
                return NotFound();
            }

            return View(commande);
        }

        // GET: Commande/Create
        public IActionResult Create()
        {
            ViewData["clientID"] = new SelectList(_context.Clients, "Id", "Id");
            ViewData["livreurID"] = new SelectList(_context.Livreurs, "Id", "Id");
            return View();
        }

        // POST: Commande/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,dateTime,montant,clientID,livreurID,CreateAt,UpdateAt")] Commande commande)
        {
            if (ModelState.IsValid)
            {
                commande.CreateAt = DateTime.Now;
                commande.UpdateAt = DateTime.Now;
                commande.Client = _context.Clients.Find(commande.ClientId);
                commande.Livreur = _context.Livreurs.Find(commande.livreurID);
                _context.Add(commande);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["clientID"] = new SelectList(_context.Clients, "Id", "Text", commande.ClientId);
            ViewData["livreurID"] = new SelectList(_context.Livreurs, "Id", "Text", commande.livreurID);
            return View(commande);
        }

        // GET: Commande/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commande = await _context.Commandes.FindAsync(id);
            if (commande == null)
            {
                return NotFound();
            }
            ViewData["clientID"] = new SelectList(_context.Clients, "Id", "Id", commande.ClientId);
            ViewData["livreurID"] = new SelectList(_context.Livreurs, "Id", "Id", commande.livreurID);
            return View(commande);
        }

        // POST: Commande/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,dateTime,montant,clientID,livreurID,CreateAt,UpdateAt")] Commande commande)
        {
            if (id != commande.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(commande);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommandeExists(commande.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["clientID"] = new SelectList(_context.Clients, "Id", "Id", commande.ClientId);
            ViewData["livreurID"] = new SelectList(_context.Livreurs, "Id", "Id", commande.livreurID);
            return View(commande);
        }

        // GET: Commande/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commande = await _context.Commandes
                .Include(c => c.Client)
                .Include(c => c.Livreur)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (commande == null)
            {
                return NotFound();
            }

            return View(commande);
        }

        // POST: Commande/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var commande = await _context.Commandes.FindAsync(id);
            if (commande != null)
            {
                _context.Commandes.Remove(commande);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommandeExists(int id)
        {
            return _context.Commandes.Any(e => e.Id == id);
        }

        public IActionResult CommandeRS()
        {
            // Vérifier si l'utilisateur est authentifié
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Securite"); // Rediriger vers la page de connexion si l'utilisateur n'est pas authentifié
            }

            // Récupérer les commandes avec l'état "En cours"
           var commandesEnCours = _context.Commandes
                                         .Include(c => c.Client)
                                         .Where(c =>c.Etat == Etat.Pret_A_LIVRER)
                                         .ToList();

            // Passer la liste des commandes à la vue
            return View(commandesEnCours);
        }

         public IActionResult CommandeComp()
        {
            // Vérifier si l'utilisateur est authentifié
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Securite"); // Rediriger vers la page de connexion si l'utilisateur n'est pas authentifié
            }

            // Récupérer les commandes avec l'état "En cours"
         var commandesEnCours = _context.Commandes
                                .Include(c => c.Client)
                               .Where(c => c.Etat == Etat.Encours)
                               .ToList();

            // Passer la liste des commandes à la vue
            return View(commandesEnCours);
        }
        public IActionResult Transferer(int id)
{
    if (!User.Identity.IsAuthenticated)
    {
        return RedirectToAction("Login", "Securite"); // Redirection si l'utilisateur n'est pas connecté
    }

    // Rechercher la commande dans la base de données
    var commande = _context.Commandes.FirstOrDefault(c => c.Id == id);
    if (commande == null)
    {
        return NotFound(); // Retourne une erreur 404 si la commande n'existe pas
    }

    // Changer l'état de la commande à "Prêt à être livré"
    commande.Etat = Etat.Pret_A_LIVRER; // Assurez-vous que "Etat.Pret_A_LIVRER" correspond à votre énumération
    _context.SaveChanges(); // Sauvegarder les modifications dans la base de données

    return RedirectToAction("CommandeRS");
}
public IActionResult Livrer(int id)
{
    // Récupération de la commande par son Id
    var commande = _context.Commandes
        .Include(c => c.Client)
        .FirstOrDefault(c => c.Id == id);

    if (commande == null)
    {
        return NotFound();
    }

    // Charger les livreurs disponibles
    var livreursDisponibles = _context.Livreurs
        .Where(l => l.Disponible)
        .Select(l => new SelectListItem
        {
            Value = l.Id.ToString(),
            Text = l.Nom + " " + l.Prenom
        }).ToList();

    ViewBag.Livreurs = livreursDisponibles;

    return View(commande);
}

[HttpPost]
public IActionResult ConfirmerLivraison(int id, DateTime dateTime, string AdresseLivraison, int livreurID)
{

Controllers/PaiementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ges_commande.Models.entity;
using GesCommande.core;
using ges_commande.Models.Enum;

namespace ges_commande.Controllers
{
    public class PaiementController : Controller
    {
        private readonly Context _context;

        public PaiementController(Context context)
        {
            _context = context;
        }

        // GET: Paiement
        public async Task<IActionResult> Index()
        {
            var context = _context.Paiements.Include(p => p.Commande);
            return View(await context.ToListAsync());
        }

        // GET: Paiement/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paiement = await _context.Paiements
                .Include(p => p.Commande)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paiement == null)
            {
                return NotFound();
            }

            return View(paiement);
        }

        // GET: Paiement/Create
        public IActionResult Create()
        {
            ViewData["CommandeId"] = new SelectList(_context.Commandes, "Id", "Id");
            return View();
        }

        // POST: Paiement/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("typePaiement,CommandeId,Id,CreateAt,UpdateAt")] Paiement paiement)
        {
            if (ModelState.IsValid)
            {
                _context.Add(paiement);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CommandeId"] = new SelectList(_context.Commandes, "Id", "Id", paiement.CommandeId);
            return View(paiement);
        }

        // GET: Paiement/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paiement = await _context.Paiements.FindAsync(id);
            if (paiement == null)
            {
                return NotFound();
            }
            ViewData["CommandeId"] = new SelectList(_context.Commandes, "Id", "Id", paiement.CommandeId);
            return View(paiement);
        }

        // POST: Paiement/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("typePaiement,CommandeId,Id,CreateAt,UpdateAt")] Paiement paiement)
        {
            if (id != paiement.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paiement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaiementExists(paiement.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CommandeId"] = new SelectList(_context.Commandes, "Id", "Id", paiement.CommandeId);
            return View(paiement);
        }

        // GET: Paiement/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paiement = await _context.Paiements
                .Include(p => p.Commande)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paiement == null)
            {
                return NotFound();
            }

            return View(paiement);
        }

        // POST: Paiement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var paiement = await _context.Paiements.FindAsync(id);
            if (paiement != null)
            {
                _context.Paiements.Remove(paiement);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaiementExists(int id)
        {
            return _context.Paiements.Any(e => e.Id == id);
        }

                [HttpGet]
public IActionResult Paiement(int id)
{
    // Vérifier si la commande existe
    var commande = _context.Commandes
                           .Include(c => c.Client)  // Charger le client associé
                           .FirstOrDefault(c => c.Id == id);

    if (commande == null)
    {
        return NotFound(); // Si la commande n'existe pas
    }

    // Passer la commande à la vue pour afficher les détails
    return View(commande);
}


[HttpPost]
[ValidateAntiForgeryToken]
public IActionResult PaiementConfirmed(int id,string moyenPaiement)
{
    // Récupérer la commande
    var commande = _context.Commandes.FirstOrDefault(c => c.Id == id);
    if (commande == null)
    {
        return NotFound();
    }
var typePaiement = TypePaiementHelper.GetValue(moyenPaiement);
    if (typePaiement == null)
    {
        return BadRequest("Moyen de paiement invalide");
    }

    // Vérifier si un paiement existe déjà, sinon en créer un
    if (commande.Paiement == null)
    {
        commande.Paiement = new Paiement();  // Créer une nouvelle instance de Paiement
    }
    // Simuler un paiement en mettant à jour l'état de la commande
    commande.Etat = Etat.Payer;
    commande.Paiement.typePaiement = typePaiement.Value;
    commande.Paiement.CreateAt = DateTime.Now;
    commande.UpdateAt = DateTime.Now;

    _context.SaveChanges();

    // Rediriger vers la liste des commandes après paiement
    return RedirectToAction("CommandeClient" ,"Commande");
}
    }
}

Views/Commande/CommandeClient.cshtml
@model IEnumerable<ges_commande.Models.entity.Commande>
@{
    Layout = "MenuClient";  
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Liste des commandes</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 text-gray-800">
    <div class="container mx-auto py-8">
        <h1 class="text-2xl font-bold mb-4 text-center">Mes commandes</h1>
        <p class="mb-4 float-right">
            <a asp-action="Create" class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">Créer une nouvelle commande</a>
        </p>
        <div class="flex justify-center mb-4">
            <form method="get" action="@Url.Action("CommandeClient")" class="mr-2 text-lg font-semibold">
                <label for="etat" class="mr-2">Filtrer par état:</label>
                <select name="etat" id="etat" class="py-3 px-4 text-lg border border-gray-300 rounded-md">
                    <option value="">Tous</option>
                    <option value="Encours">En cours</option>
                    <option value="Payer">Payer</option>
                    <option value="Annuler">Annuler</option>
                </select>
                <button type="submit" class="ml-2 bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600">Filtrer</button>
            </form>
        </div>
        <div class="overflow-x-auto">
            <table class="table-auto w-full bg-white shadow-md rounded border border-blue-600">
                <thead class="bg-blue-600 text-white uppercase text-sm leading-normal">
                    <tr>
                        <th class="py-3 px-6 text-center">Date</th>
                        <th class="py-3 px-6 text-left">@Html.DisplayNameFor(model => model.montant)</th>
                        <th class="py-3 px-6 text-center">Etat</th>
                        <th class="py-3 px-6 text-center">Actions</th>
                    </tr>
                </thead>
                <tbody class="text-gray-600 text-sm font-light">
                    @foreach (var item in Model) {
                        <tr class="border-b border-blue-200 hover:bg-blue-50">
                            <td class="py-3 px-9 text-center">@Convert.ToDateTime(item.CreateAt).ToString("dd/MM/yyyy")</td>        
                            <td class="py-3 px-6 text-left">@Html.DisplayFor(modelItem => item.montant)</td>
                            <td class="py-3 px-6 text-center">@item.Etat</td>
                            <td class="py-3 px-6 text-center">
                                <a asp-controller="Paiement" asp-action="Paiement" asp-route-id="@item.Id" class="text-blue-500 hover:underline">Payer</a>
                                <a asp-action="Details" asp-route-id="@item.Id" class="text-green-500 hover:underline">Détails</a> |
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

Views/Commande/CommandeComp.cshtml
@model IEnumerable<ges_commande.Models.entity.Commande>

@{
   @* Layout= "_Layout"; *@
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 text-gray-800">
    <div class="container mx-auto py-8">
        <h1 class="text-2xl font-bold mb-4">Liste des commandes</h1>
        <div class="overflow-x-auto">
            <table class="table-auto w-full bg-white shadow-md rounded border border-blue-600">
                <thead class="bg-blue-600 text-white uppercase text-sm leading-normal">
                    <tr>
                        <th class="py-3 px-6 text-center">Date</th>
                        <th class="py-3 px-6 text-left">@Html.DisplayNameFor(model => model.montant)</th>
                        <th class="py-3 px-6 text-left">@Html.DisplayNameFor(model => model.Client)</th>
                        <th class="py-3 px-6 text-left">Etat</th>
                        <th class="py-3 px-6 text-center">Actions</th>
                    </tr>
                </thead>
                <tbody class="text-gray-600 text-sm font-light">
                    @foreach (var item in Model) {
                        <tr class="border-b border-blue-200 hover:bg-blue-50">
                            <td class="py-3 px-6 text-left">@Html.DisplayFor(modelItem => item.CreateAt)</td>
                            <td class="py-3 px-6 text-left">@Html.DisplayFor(modelItem => item.montant) FCFA</td>
                            <td class="py-3 px-6 text-left">
                                @Html.DisplayFor(modelItem => item.Client.Prenom) 
                                @Html.DisplayFor(modelItem => item.Client.Nom)
                            </td>
                            <td class="py-3 px-6 text-left">
                                <span class="text-blue-500">@Html.DisplayFor(modelItem => item.Etat)</span>
                            </td>
                            <td class="py-3 px-6 text-center">
                                <a asp-action="transferer" asp-route-id="@item.Id" class="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition duration-200">Transférer</a> 
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

Views/Commande/CommandeRS.cshtml
@model IEnumerable<ges_commande.Models.entity.Commande>

@{
   @* Layout= "_Layout"; *@
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 text-gray-800">
    <div class="container mx-auto py-8">
        <h1 class="text-2xl font-bold mb-4">Liste des commandes</h1>

        <div class="overflow-x-auto">
            <table class="table-auto w-full bg-white shadow-md rounded border border-blue-600">
                <thead class="bg-blue-600 text-white uppercase text-sm leading-normal">
                    <tr>
                        <th class="py-3 px-6 text-center">Date</th>
                        <th class="py-3 px-6 text-left">@Html.DisplayNameFor(model => model.montant)</th>
                        <th class="py-3 px-6 text-left">@Html.DisplayNameFor(model => model.Client)</th>
                        <th class="py-3 px-6 text-left">Etat</th>
                        <th class="py-3 px-6 text-center">Actions</th>
                    </tr>
                </thead>
                <tbody class="text-gray-600 text-sm font-light">
                    @foreach (var item in Model) {
                        <tr class="border-b border-blue-200 hover:bg-blue-50">
                            <td class="py-3 px-6 text-left">@Html.DisplayFor(modelItem => item.CreateAt)</td>
                            <td class="py-3 px-6 text-left">@Html.DisplayFor(modelItem => item.montant)</td>
                            <td class="py-3 px-6 text-left">
                                @Html.DisplayFor(modelItem => item.Client.Prenom) 
                                @Html.DisplayFor(modelItem => item.Client.Nom)
                            </td>     
                            <td class="py-3 px-6 text-left text-green-600 ">@Html.DisplayFor(modelItem => item.Etat)</td>
                            <td class="py-3 px-6 text-center">
                                <a asp-action="Livrer" asp-route-id="@item.Id" class="bg-blue-700 text-white px-4 py-2 rounded hover:bg-blue-800 transition duration-200">Prêt à être livré</a> 
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

Views/Commande/Create.cshtml
@model ges_commande.Models.entity.Commande

@{
    @* Layout= "_Layout"; *@
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-blue-100">
    <div class="container mx-auto p-4 mt-4 bg-blue-200 rounded-lg shadow-md">
        <h4 class="text-3xl font-bold mb-4 text-blue-800">Créer une nouvelle commande</h4>
        <hr class="mb-4" />
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="grid grid-cols-2 gap-4">
                <div class="bg-white rounded-lg shadow-md p-4">
                    <div class="form-group mb-4">
                        <label asp-for="dateTime" class="control-label text-blue-800 font-bold text-lg"></label>
                        <input asp-for="dateTime" class="form-control rounded-lg shadow-md p-2 border border-blue-400 text-lg" />
                        <span asp-validation-for="dateTime" class="text-danger text-lg"></span>
                    </div>
                    <div class="form-group mb-4">
                        <label asp-for="montant" class="control-label text-blue-800 font-bold text-lg"></label>
                        <input asp-for="montant" class="form-control rounded-lg shadow-md p-2 border border-blue-400 text-lg" />
                        <span asp-validation-for="montant" class="text-danger text-lg"></span>
                    </div>
                </div>
                <div class="bg-white rounded-lg shadow-md p-4">
                    <div class="form-group mb-4">
                        <label asp-for="ClientId" class="control-label text-blue-800 font-bold text-lg"></label>
                        <select asp-for="ClientId" class="form-control rounded-lg shadow-md p-2 border border-blue-400 text-lg" asp-items="ViewBag.clientID"></select>
                    </div>
                    <div class="form-group mb-4">
                        <label asp-for="livreurID" class="control-label text-blue-800 font-bold text-lg"></label>
                        <select asp-for="livreurID" class="form-control rounded-lg shadow-md p-2 border border-blue-400 text-lg" asp-items="ViewBag.livreurID"></select>
                    </div>
                </div>
            </div>
           
            <div class="grid grid-cols-2 gap-4">
                <div class="bg-white rounded-lg shadow-md p-4">
                    <div class="form-group mb-4">
                        <label asp-for="CreateAt" class="control-label text-blue-800 font-bold text-lg"></label>
                        <input asp-for="CreateAt" class="form-control rounded-lg shadow-md p-2 border border-blue-400 text-lg" />
                        <span asp-validation-for="CreateAt" class="text-danger text-lg"></span>
                    </div>
                </div>
            </div>
            <div class="form-group mb-4">
                <input type="submit" value="Créer" class="btn btn-primary rounded-lg shadow-md p-2 bg-blue-500 hover:bg-blue-700 text-white text-lg" />
            </div>
    </form>
    <div class="flex justify-center mt-4">
        <a asp-action="MesCommande" class="text-blue-800 font-bold hover:text-blue-500 text-lg">Retour à la liste</a>
    </div>
</div>
</body>
</html>

Views/Commande/Details.cshtml
@model ges_commande.Models.entity.Commande

@{
   @* Layout= "_Layout"; *@
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Détails</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">
    <div class="container mx-auto p-8 mt-10 bg-white shadow-md rounded-lg">
        <h4 class="text-2xl font-bold text-gray-800 mb-6">Détails de la commande</h4>
        <hr class="border-gray-300 mb-6" />
        <dl class="grid grid-cols-1 md:grid-cols-2 gap-x-4 gap-y-2">
            <div>
                <dt class="text-sm font-medium text-gray-500">
                    @Html.DisplayNameFor(model => model.dateTime)
                </dt>
                <dd class="text-lg text-gray-800">
                    @Html.DisplayFor(model => model.dateTime)
                </dd>
            </div>
            <div>
                <dt class="text-sm font-medium text-gray-500">
                    @Html.DisplayNameFor(model => model.montant)
                </dt>
                <dd class="text-lg text-gray-800">
                    @Html.DisplayFor(model => model.montant)
                </dd>
            </div>
            <div>
                <dt class="text-sm font-medium text-gray-500">
                    @Html.DisplayNameFor(model => model.Client)
                </dt>
                <dd class="text-lg text-gray-800">
                    @Html.DisplayFor(model => model.Client.Id)
                </dd>
            </div>
            <div>
                <dt class="text-sm font-medium text-gray-500">
                    @Html.DisplayNameFor(model => model.Livreur)
                </dt>
                <dd class="text-lg text-gray-800">
                    @Html.DisplayFor(model => model.Livreur.Id)
                </dd>
            </div>
            <div>
                <dt class="text-sm font-medium text-gray-500">
                    @Html.DisplayNameFor(model => model.CreateAt)
                </dt>
                <dd class="text-lg text-gray-800">
                    @Html.DisplayFor(model => model.CreateAt)
                </dd>
            </div>
            <div>
                <dt class="text-sm font-medium text-gray-500">
                    @Html.DisplayNameFor(model => model.UpdateAt)
                </dt>
                <dd class="text-lg text-gray-800">
                    @Html.DisplayFor(model => model.UpdateAt)
                </dd>
            </div>
        </dl>
        <div class="flex items-center space-x-4 mt-8">
            <a asp-action="Payer" asp-route-id="@Model?.Id" class="bg-blue-500 text-white px-6 py-2 rounded-md hover:bg-blue-600 shadow-md">Payer</a>
            <a asp-action="CommandeClient" class="bg-gray-200 text-gray-800 px-6 py-2 rounded-md hover:bg-gray-300 shadow-md">Retour à la liste</a>
        </div>
    </div>
</body>
</html>